name: 报告 Bug
description: 报告一个 Bug 以帮助我们改进
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: 版本号
      description: 您正在使用的纪程版本？
      placeholder: 0.14.1
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: 操作系统
      description: 您正在使用哪个操作系统？
      options:
        - macOS
        - Windows
        - Linux
      default: 0
    validations:
      required: true
  - type: dropdown
    id: distribution
    attributes:
      label: 安装方式
      description: 您使用哪种安装包？
      options:
        - dmg (Mac OS - Apple Silicon)
        - dmg (Mac OS - Intel)
        - msi (Windows)
        - winget (Windows)
        - deb (Linux)
        - rpm (Linux)
        - AppImage (Linux)
        - Flatpak (Linux)
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请描述您遇到的问题以及您已尝试的解决方法。可以在此处添加任何有用的信息，也可以使用截图或视频说明。
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: 复现步骤（可选）
      description: 如何触发这个 Bug？请逐步说明。
      placeholder: |
        1. ...
        2. ...
        3. ...
        ...
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 预期行为（可选）
      description: 描述您原本期望发生的情况。
      placeholder: |
        1. 设置 ... 选项不应导致应用崩溃
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 相关日志输出（可选）
      description: 请复制并粘贴相关的日志输出。将自动格式化为代码，无需添加反引号。
      render: shell
    validations:
      required: false
