name: 功能请求
description: 提出一个新功能建议
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: 解决的问题
      description: 这个功能请求与某个问题相关吗？请清晰描述该问题。例如：当 [...] 时，我总是感到困扰。
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案
      description: 请清晰描述您希望发生的情况。
      placeholder: 如果能够 [...] 就好了。
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 考虑过的替代方案（可选）
      description: 您是否考虑过其他替代方案或变通方法？
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: 附加上下文（可选）
      description: 添加任何其他上下文、截图或关于功能请求的说明。
    validations:
      required: false
